### ISSUE TITLE
The social media icons are not redirecting to the respective social media platforms when clicked.

### ISSUE THREAD

**Issue by wgeenath** [pranjalee30/cake#11]
Issue :

The social media icons are not redirecting to the respective social media platforms when clicked.

![image](https://github.com/user-attachments/assets/6e95e385-3918-44d9-bb38-c8824d3164e0)

Please assign this task to me. If you have specific links for the social media platforms, kindly attach them here. Otherwise, I can redirect the icons to the respective social media homepages.

**Comment by FSfarhaan** [comment]
Hello, can I work on this issue?

**Comment by pranjalee30** [comment]
> Hello, can I work on this issue?

No need of this now
