### ISSUE TITLE
Put updated social media logo and fix bug in card

### ISSUE THREAD

**Issue by nileshkr022** [pranjalee30/cake#12]
- There is old logo of X on footer , I want to change it into new logo with suitable hover color 
- the buttons in card move slightly when hovered. I want to fix that to make uniformity with suitable hovering effect.

**Comment by pranjalee30** [comment]
@nileshkr022  ok sure, Give me some time, I will do it by today.

**Comment by nileshkr022** [comment]
> - There is old logo of X on footer , I want to change it into new logo with suitable hover color 
> - the buttons in card move slightly when hovered. I want to fix that to make uniformity with suitable hovering effect.

@pranjalee30  Can you put hacktoberfest2024 label on it?
