### ISSUE TITLE
Add More Cake Cards by Updating the JSON Data

### ISSUE THREAD

**Issue by pranjalee30** [pranjalee30/cake#3]
**Issue Description:**
Context: Currently, the website displays a set of cake cards based on the data from a JSON file. To expand the cake selection, we would like to add more cakes to the catalog by updating the JSON file that contains the cake data.

**Task:**

Add at least 10 more cake entries in the JSON file.
Ensure that each entry includes the following fields:
Cake Name
Cake Image URL
Flavor
Price
Short description
Ensure that the new cakes appear properly in the UI and match the existing design.

**Steps:**

Update the existing JSON file with 5 new cakes.
Test the changes to ensure that the new cakes are displayed correctly on the "Our Cakes" section of the website.
**Additional Notes:**
Ensure that the images used are high-quality and consistent with the existing cakes.
Test the responsiveness of the cake cards with the new additions to ensure they display correctly across all devices.
If you're interested in working on this issue, feel free to assign yourself!

**Comment by Abhiraj-Sardar** [comment]
Hey @pranjalee30 ,

I want to work on this issue, can you assign this to me?

**Comment by pranjalee30** [comment]
@Abhiraj-Sardar done !

**Comment by biswajit-sarkar-007** [comment]
Hello! I'm interested in this issue. Can I be assigned?

**Comment by Abhiraj-Sardar** [comment]
hi @pranjalee30 ,
i just made a pull request , please review and merge it.

once everything is ok. You can close this issue.
Thank You

**Comment by pranjalee30** [comment]
> hi @pranjalee30 , i just made a pull request , please review and merge it.
> 
> once everything is ok. You can close this issue. Thank You



[checkout this](https://github.com/pranjalee30/cake/pull/7#pullrequestreview-2349535593)
